import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTableProductvariant1710987457026
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
    CREATE TABLE "product_variant" (
        "id"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" VARCHAR(255) NOT NULL,
        "product_code" VARCHAR(255) NOT NULL,
        "product_id" BIGINT,
        "price" DECIMAL NOT NULL, 
        "discount_rate" INT NOT NULL,
        "inventory" INT NOT NULL,
        "image_id" BIGINT NOT NULL,
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT now(), 
        "deleted_at" TIMESTAMP
      );
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "product_variant";`);
  }
}
