import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTableProduct1710987243863 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
    CREATE TABLE "product" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" VARCHAR(255) NOT NULL,
        "description" TEXT,
        "category_id" BIGINT NOT NULL,
        "image_id" BIGINT NOT NULL,
        "is_best_seller" INT DEFAULT 0,
        "rating" REAL DEFAULT 0.0,
        "sold" INT DEFAULT 0,
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT now(), 
        "deleted_at" TIMESTAMP
      );
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "product";`);
  }
}
