import { MigrationInterface, QueryRunner } from 'typeorm';

export class $npmConfigName1710902932694 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "user" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"email" character varying NOT NULL,"password" character varying NOT NULL,
        "image" character varying NOT NULL,
        "role" character varying(10) NOT NULL,"created_at" TIMESTAMP NOT NULL DEFAULT now(),"updated_at" TIMESTAMP NOT NULL DEFAULT now(),"deleted_at" TIMESTAMP);`,
    );
    await queryRunner.query(`CREATE TABLE "token" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"user_id" BIGINT NOT NULL,"token" character varying NOT NULL,
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
        "deleted_at" TIMESTAMP
      );`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "user";`);
    await queryRunner.query(`DROP TABLE "token";`);
  }
}
