import { MigrationInterface, QueryRunner } from 'typeorm';

export class $npmConfigName1710904895486 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "category" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" VARCHAR(100),
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT now(), 
        "deleted_at" TIMESTAMP);`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "category";`);
  }
}
