import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTableAddress1711592183211 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
    CREATE TABLE "address" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" BIGINT NOT NULL,
        "province" VARCHAR(100) NOT NULL,
        "district" VARCHAR(100) NOT NULL,
        "ward" VARCHAR(100) NOT NULL,
        "detail_address" VARCHAR(500) NOT NULL,
        "phone_number" VARCHAR(20) NOT NULL,
        "fullname" VARCHAR,
        "is_active" INT DEFAULT 0,
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
        "deleted_at" TIMESTAMP
    );
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
    DROP TABLE "cart_item";
    `);
  }
}
