import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTableCartItem1711265075441 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        CREATE TABLE "cart_item" (
            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "user_id" BIGINT NOT NULL,
            "order_id" BIGINT,
            "product_variant_id" BIGINT NOT NULL,
            "quantity" INT NOT NULL,
            "created_at" TIMESTAMP NOT NULL DEFAULT now(),
            "updated_at" TIMESTAMP NOT NULL DEFAULT now(), 
            "deleted_at" TIMESTAMP
        );
            `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        DROP TABLE "cart_item";`);
  }
}
