import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTableOrder1712286684867 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
    CREATE TABLE "order" (
        "id"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" BIGINT NOT NULL,
        "note" TEXT,
        "order_code" VARCHAR(100),
        "status" VARCHAR NOT NULL,
        "payment_method" VARCHAR NOT NULL DEFAULT 'COD',
       
        "total_money" FLOAT NOT NULL,
        "fee_shipping" FLOAT NOT NULL,
        "province" VARCHAR(100) NOT NULL,
        "district" VARCHAR(100) NOT NULL,
        "ward" VARCHAR(100) NOT NULL,
        "detail_address" VARCHAR(500) NOT NULL,
        "phone_number" VARCHAR(20),
        "fullname" VARCHAR(255),
        "expected_shipping_date" TIMESTAMP,
        "actual_shipping_date" TIMESTAMP,
        "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        "deleted_at" TIMESTAMP WITHOUT TIME ZONE
    );
    
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "order";`);
  }
}
